---
- name: Set Apt Cache NG
  ansible.builtin.template:
    src: apt.conf.d/01proxy.j2
    dest: /etc/apt/apt.conf.d/01proxy
    owner: root
    group: root
    mode: '0644'
  when: group_vars.apt_cache_ng.url is defined
