---
- name: "Look up k8s_joining_token"
  set_fact:
    k8s_joining_token: "{{ lookup('ansible.builtin.file', './.k8s_joining_token.txt') }}"

- name: "Failed if a variable k8s_joining_token has empty"
  ansible.builtin.fail:
    msg: "ERROR: A variable \"k8s_joining_token\" has empty. It might also mean that getting k8s_joining_token from k8s master node has failed."
  when: k8s_joining_token == ""

- name: "Look up k8s_discovery_token_ca_cert_hash.txt"
  set_fact:
    k8s_discovery_token_ca_cert_hash: "{{ lookup('ansible.builtin.file', './.k8s_discovery_token_ca_cert_hash.txt') }}"

- name: "Failed if a variable k8s_discovery_token_ca_cert_hash has empty"
  ansible.builtin.fail:
    msg: "ERROR: A variable \"k8s_discovery_token_ca_cert_hash\" has empty. It might also mean that getting k8s_discovery_token_ca_cert_hash from k8s master node has failed."
  when: k8s_discovery_token_ca_cert_hash == ""

#- name: "Debug variables \"k8s_joining_token\" and \"k8s_discovery_token_ca_cert_hash\""
#  ansible.builtin.debug:
#    msg: "k8s_joining_token={{ k8s_joining_token }}, k8s_discovery_token_ca_cert_hash={{ k8s_discovery_token_ca_cert_hash }}"

- name: "Run a command \"kubeadm join <master_node_ip:port> --token <token> --discovery-token-ca-cert-hash <hash>\""
  ansible.builtin.command:
    argv: ["kubeadm", "join", "192.168.255.11:6443", "--token", "{{ k8s_joining_token }}", "--discovery-token-ca-cert-hash", "sha256:{{ k8s_discovery_token_ca_cert_hash }}"]
  args:
    creates: "/root/.kubeadm_join_has_already_done"

- name: "Create \"/root/.kubeadm_join_has_already_done\" if \"kubeadm join <master_node_ip:port> --token <token> --discovery-token-ca-cert-hash <hash>\" was succeeded"
  ansible.builtin.file:
    path: "/root/.kubeadm_join_has_already_done"
    state: touch
    mode: '0640'
