---
- name: Run sysctl system
  command: sysctl --system

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
