---
- name: "Include init_k8s_cluster/main.yml"
  include_tasks: init_k8s_cluster/main.yml

- name: "Include prepare_calico_network/main.yml"
  include_tasks: prepare_calico_network/main.yml

- name: "Include prepare_weave_daemonset/main.yml"
  include_tasks: prepare_weave_daemonset/main.yml

- name: "Inlcude get_tokens_for_joining_k8s_cluster/main.yml"
  include_tasks: get_tokens_for_joining_k8s_cluster/main.yml
