---
# Preparing weave net to be ready to each k8s nodes.

- name: "Download a manifest of Weave daemon set."
  get_url:
    url: https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
    dest: "{{ ansible_env.HOME }}/weave-daemonset-k8s.yaml"

- name: "Apply Weave daemonset with a command \"kubectl apply -f {{ ansible_env.HOME }}/weave-daemonset-k8s.yaml\""
  shell: "kubectl apply -f {{ ansible_env.HOME }}/weave-daemonset-k8s.yaml"
  register: kubectl_result
  retries: 360
  delay: 5
  timeout: 10
  until: kubectl_result is success

